server:
  port: 8761

spring:
  application:
    name: eureka-server         # 应用名称
  security:
    user:
      name: root
      password: 123456

management:
  endpoint:
    shutdown:
      enabled: true

eureka:
  instance:
    hostname: localhost         # 主机名，不配置的时候根据操作系统的主机名来获取
    prefer-ip-address: true    # 是否按ip地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #ip:port
  client:
    registerWithEureka: false  # 是否将自己注册到注册中心 默认true
    fetchRegistry: false       # 是否从注册中心获取服务注册信息 默认true
    serviceUrl:                # 注册中心对外暴露的注册地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
